/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_home (void)
{
  GtkWidget *home;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *button2;
  GtkWidget *button1;

  home = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (home, 500, 400);
  gtk_window_set_title (GTK_WINDOW (home), _("home"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (home), fixed1);

  label1 = gtk_label_new (_("MYGYM"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 168, 16);
  gtk_widget_set_size_request (label1, 80, 56);

  button2 = gtk_button_new_with_mnemonic (_("signin"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 368, 104);
  gtk_widget_set_size_request (button2, 66, 29);

  button1 = gtk_button_new_with_mnemonic (_("login"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 368, 56);
  gtk_widget_set_size_request (button1, 66, 29);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (home, home, "home");
  GLADE_HOOKUP_OBJECT (home, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (home, label1, "label1");
  GLADE_HOOKUP_OBJECT (home, button2, "button2");
  GLADE_HOOKUP_OBJECT (home, button1, "button1");

  return home;
}

GtkWidget*
create_authentification (void)
{
  GtkWidget *authentification;
  GtkWidget *fixed2;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label2;
  GtkWidget *label562;
  GtkWidget *button3;
  GtkWidget *alignment7;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label561;

  authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (authentification, 480, 240);
  gtk_window_set_title (GTK_WINDOW (authentification), _("authentification"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (authentification), fixed2);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 152, 80);
  gtk_widget_set_size_request (entry1, 312, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 152, 136);
  gtk_widget_set_size_request (entry2, 312, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label2 = gtk_label_new (_("<span font_desc=\"italic\" foreground =\"black\" size=\"large\"><b>loggin</b></span>"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 16, 80);
  gtk_widget_set_size_request (label2, 120, 25);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  label562 = gtk_label_new (_("<span font_desc=\"italic\" foreground =\"black\" size=\"large\"><b>password</b></span>"));
  gtk_widget_show (label562);
  gtk_fixed_put (GTK_FIXED (fixed2), label562, 16, 136);
  gtk_widget_set_size_request (label562, 120, 25);
  gtk_label_set_use_markup (GTK_LABEL (label562), TRUE);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 320, 200);
  gtk_widget_set_size_request (button3, 154, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button3), alignment7);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label561 = gtk_label_new (_("<span font_desc=\"italic\" foreground =\"black\" size=\"large\">logins</span>"));
  gtk_widget_show (label561);
  gtk_box_pack_start (GTK_BOX (hbox6), label561, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label561, 66, -1);
  gtk_label_set_use_markup (GTK_LABEL (label561), TRUE);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification, authentification, "authentification");
  GLADE_HOOKUP_OBJECT (authentification, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (authentification, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (authentification, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (authentification, label2, "label2");
  GLADE_HOOKUP_OBJECT (authentification, label562, "label562");
  GLADE_HOOKUP_OBJECT (authentification, button3, "button3");
  GLADE_HOOKUP_OBJECT (authentification, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (authentification, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (authentification, image7, "image7");
  GLADE_HOOKUP_OBJECT (authentification, label561, "label561");

  return authentification;
}

GtkWidget*
create_admin (void)
{
  GtkWidget *admin;
  GtkWidget *vbox6;
  GtkWidget *vbox7;
  GtkWidget *image12;
  GtkWidget *notebook3;
  GtkWidget *vbox11;
  GtkWidget *fixed23;
  GtkWidget *label582;
  GtkWidget *hbox10;
  GtkWidget *list1;
  GtkWidget *curve1;
  GtkWidget *calendar1;
  GtkWidget *hbox9;
  GtkWidget *list2;
  GtkWidget *label573;
  GtkWidget *notebook1;
  GtkWidget *vbox1;
  GtkWidget *vbox8;
  GtkWidget *label42;
  GtkWidget *vbox9;
  GtkWidget *label576;
  GtkWidget *affichetree;
  GtkWidget *fixed21;
  GtkWidget *vbox10;
  GtkWidget *hbuttonbox1;
  GtkWidget *refraiche;
  GtkWidget *button16;
  GtkWidget *button17;
  GtkWidget *scrolledwindow2;
  GtkWidget *viewport1;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview1;
  GtkWidget *label38;
  GtkWidget *vbox2;
  GtkWidget *label43;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview3;
  GtkWidget *fixed17;
  GtkWidget *label39;
  GtkWidget *vbox3;
  GtkWidget *label54;
  GtkWidget *fixed11;
  GtkObject *spinbutton26_adj;
  GtkWidget *spinbutton26;
  GtkWidget *label55;
  GtkWidget *modifier_as_admin;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label548;
  GtkWidget *supprimer_as_admin;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *supprime123;
  GtkWidget *fixed12;
  GtkWidget *label572;
  GtkWidget *fixed13;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkWidget *label62;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkObject *spinbutton13_adj;
  GtkWidget *spinbutton13;
  GtkObject *spinbutton14_adj;
  GtkWidget *spinbutton14;
  GtkWidget *label64;
  GtkWidget *label60;
  GtkWidget *entry6;
  GtkObject *spinbutton15_adj;
  GtkWidget *spinbutton15;
  GtkWidget *entry7;
  GtkObject *spinbutton16_adj;
  GtkWidget *spinbutton16;
  GtkWidget *entry105;
  GtkWidget *label56;
  GtkWidget *label567;
  GtkWidget *label57;
  GtkWidget *label61;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *label67;
  GtkWidget *label63;
  GtkWidget *label68;
  GtkWidget *combobox3;
  GtkWidget *label69;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label568;
  GtkWidget *entry106;
  GtkWidget *label90;
  GtkWidget *button13;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label515;
  GtkWidget *combobox4;
  GtkWidget *label569;
  GtkWidget *label571;
  GtkWidget *label570;
  GtkWidget *label574;
  GtkWidget *vbox12;
  GtkWidget *hbox11;
  GtkWidget *image10;
  GtkWidget *fixed22;
  GtkWidget *entry107;
  GtkWidget *entry108;
  GtkWidget *label580;
  GtkWidget *label579;
  GtkWidget *label578;
  GtkWidget *ajouter_admin;
  GtkWidget *alignment10;
  GtkWidget *hbox12;
  GtkWidget *image11;
  GtkWidget *label581;
  GtkWidget *treeview4;
  GtkWidget *label575;
  GtkWidget *fixed19;

  admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (admin, 1240, 900);
  gtk_window_set_title (GTK_WINDOW (admin), _("admin 0.3"));

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (admin), vbox6);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), vbox7, TRUE, TRUE, 0);

  image12 = create_pixmap (admin, "47442522_499464947230172_3566078205901144064_n.png");
  gtk_box_pack_start (GTK_BOX (vbox7), image12, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (image12, FALSE);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_box_pack_start (GTK_BOX (vbox7), notebook3, TRUE, TRUE, 0);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (notebook3), vbox11);

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_box_pack_start (GTK_BOX (vbox11), fixed23, TRUE, TRUE, 0);

  label582 = gtk_label_new (_("<span font_desc=\"italic\" foreground =\"red\" size=\"large\"><b>MyGym</b></span>"));
  gtk_widget_show (label582);
  gtk_fixed_put (GTK_FIXED (fixed23), label582, 528, 24);
  gtk_widget_set_size_request (label582, 288, 72);
  gtk_label_set_use_markup (GTK_LABEL (label582), TRUE);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox10, TRUE, TRUE, 0);

  list1 = gtk_list_new ();
  gtk_widget_show (list1);
  gtk_box_pack_start (GTK_BOX (hbox10), list1, TRUE, TRUE, 0);

  curve1 = gtk_curve_new ();
  gtk_widget_show (curve1);
  gtk_box_pack_start (GTK_BOX (hbox10), curve1, TRUE, TRUE, 0);
  gtk_curve_set_range (GTK_CURVE (curve1), 0, 1, 0, 1);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_box_pack_end (GTK_BOX (hbox10), calendar1, FALSE, FALSE, 3);
  gtk_widget_set_size_request (calendar1, 400, 10);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox9, TRUE, TRUE, 0);

  list2 = gtk_list_new ();
  gtk_widget_show (list2);
  gtk_box_pack_start (GTK_BOX (hbox9), list2, TRUE, TRUE, 0);

  label573 = gtk_label_new (_("home_admin"));
  gtk_widget_show (label573);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label573);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (notebook3), notebook1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox1);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), vbox1,
                                      TRUE, TRUE, GTK_PACK_START);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox8, FALSE, FALSE, 0);

  label42 = gtk_label_new (_("<span font_desc=\"Purisa\" foreground =\"purple\" size=\"large\"><b>Afichage des compts des Adherents</b></span>"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (vbox8), label42, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label42, -1, 80);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox9, FALSE, FALSE, 0);

  label576 = gtk_label_new (_("label576"));
  gtk_widget_show (label576);
  gtk_box_pack_start (GTK_BOX (vbox9), label576, FALSE, FALSE, 0);

  affichetree = gtk_button_new_with_mnemonic (_("button16"));
  gtk_widget_show (affichetree);
  gtk_box_pack_start (GTK_BOX (vbox9), affichetree, FALSE, FALSE, 0);

  fixed21 = gtk_fixed_new ();
  gtk_widget_show (fixed21);
  gtk_box_pack_start (GTK_BOX (vbox9), fixed21, TRUE, TRUE, 0);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox10, TRUE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox10), hbuttonbox1, TRUE, TRUE, 0);

  refraiche = gtk_button_new_with_mnemonic (_("button15"));
  gtk_widget_show (refraiche);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), refraiche);
  GTK_WIDGET_SET_FLAGS (refraiche, GTK_CAN_DEFAULT);

  button16 = gtk_button_new_with_mnemonic (_("button16"));
  gtk_widget_show (button16);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button16);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  button17 = gtk_button_new_with_mnemonic (_("button17"));
  gtk_widget_show (button17);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button17);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport1);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (viewport1), scrolledwindow3);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview1);
  gtk_tree_view_set_hover_expand (GTK_TREE_VIEW (treeview1), TRUE);

  label38 = gtk_label_new (Q_("<span font_desc=\"Purisa\" foreground =\"purple\" size=\"large\"><b>Adherent</b></span>"));
  gtk_widget_show (label38);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label38);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), vbox2,
                                      TRUE, TRUE, GTK_PACK_START);

  label43 = gtk_label_new (_("<span font_desc=\"Purisa\" foreground =\"purple\" size=\"large\"><b>Afichage des compts des Staff Medicalle:</b></span>"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (vbox2), label43, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label43, -1, 80);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview3);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_box_pack_start (GTK_BOX (vbox2), fixed17, TRUE, TRUE, 0);

  label39 = gtk_label_new (_("<span font_desc=\"Purisa\" foreground =\"purple\" size=\"large\"><b>Staff_medecale_et_coachs</b></span>"));
  gtk_widget_show (label39);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label39);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox3);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), vbox3,
                                      TRUE, TRUE, GTK_PACK_START);

  label54 = gtk_label_new (_("<span font_desc=\"Purisa\" foreground =\"blue\" size=\"large\"><b>si vous voulez modifier un compt existant entrer  son cart cin</b></span>"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (vbox3), label54, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label54, -1, 120);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_box_pack_start (GTK_BOX (vbox3), fixed11, TRUE, TRUE, 0);

  spinbutton26_adj = gtk_adjustment_new (1, 0, 100000000, 1, 10, 10);
  spinbutton26 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton26_adj), 1, 0);
  gtk_widget_show (spinbutton26);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton26, 432, 72);
  gtk_widget_set_size_request (spinbutton26, 268, 27);

  label55 = gtk_label_new (_("CIN:"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed11), label55, 328, 72);
  gtk_widget_set_size_request (label55, 72, 25);

  modifier_as_admin = gtk_button_new ();
  gtk_widget_show (modifier_as_admin);
  gtk_fixed_put (GTK_FIXED (fixed11), modifier_as_admin, 416, 160);
  gtk_widget_set_size_request (modifier_as_admin, 120, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (modifier_as_admin), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label548 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label548);
  gtk_box_pack_start (GTK_BOX (hbox4), label548, FALSE, FALSE, 0);

  supprimer_as_admin = gtk_button_new ();
  gtk_widget_show (supprimer_as_admin);
  gtk_fixed_put (GTK_FIXED (fixed11), supprimer_as_admin, 608, 160);
  gtk_widget_set_size_request (supprimer_as_admin, 112, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (supprimer_as_admin), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  supprime123 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (supprime123);
  gtk_box_pack_start (GTK_BOX (hbox5), supprime123, FALSE, FALSE, 0);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_box_pack_start (GTK_BOX (vbox3), fixed12, TRUE, TRUE, 0);

  label572 = gtk_label_new (_("<span font_desc=\"Purisa\" foreground =\"purple\" size=\"large\"><b>Gerer_compts</b></span>"));
  gtk_widget_show (label572);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label572);
  gtk_label_set_use_markup (GTK_LABEL (label572), TRUE);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed13);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), fixed13,
                                      TRUE, TRUE, GTK_PACK_START);

  spinbutton9_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton9, 88, 328);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  spinbutton10_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton10, 224, 328);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  label62 = gtk_label_new (_("mois"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed13), label62, 160, 328);
  gtk_widget_set_size_request (label62, 49, 25);

  spinbutton11_adj = gtk_adjustment_new (2018, 2018, 2100, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton11, 368, 328);
  gtk_widget_set_size_request (spinbutton11, 60, 27);

  spinbutton12_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton12, 88, 416);
  gtk_widget_set_size_request (spinbutton12, 60, 27);

  spinbutton13_adj = gtk_adjustment_new (2018, 2018, 2101, 1, 10, 10);
  spinbutton13 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton13_adj), 1, 0);
  gtk_widget_show (spinbutton13);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton13, 360, 416);
  gtk_widget_set_size_request (spinbutton13, 60, 27);

  spinbutton14_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton14 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton14_adj), 1, 0);
  gtk_widget_show (spinbutton14);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton14, 224, 416);
  gtk_widget_set_size_request (spinbutton14, 60, 27);

  label64 = gtk_label_new (_("date fin"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed13), label64, 152, 376);
  gtk_widget_set_size_request (label64, 152, 32);

  label60 = gtk_label_new (_("date debut"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed13), label60, 144, 288);
  gtk_widget_set_size_request (label60, 170, 25);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed13), entry6, 104, 96);
  gtk_widget_set_size_request (entry6, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  spinbutton15_adj = gtk_adjustment_new (0, 0, 100000000, 1, 10, 10);
  spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton15_adj), 1, 0);
  gtk_widget_show (spinbutton15);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton15, 104, 192);
  gtk_widget_set_size_request (spinbutton15, 184, 27);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed13), entry7, 128, 536);
  gtk_widget_set_size_request (entry7, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  spinbutton16_adj = gtk_adjustment_new (1, 0, 100000000, 1, 10, 10);
  spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton16_adj), 1, 0);
  gtk_widget_show (spinbutton16);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton16, 128, 488);
  gtk_widget_set_size_request (spinbutton16, 184, 27);

  entry105 = gtk_entry_new ();
  gtk_widget_show (entry105);
  gtk_fixed_put (GTK_FIXED (fixed13), entry105, 104, 144);
  gtk_widget_set_size_request (entry105, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry105), 8226);

  label56 = gtk_label_new (_("nom:"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed13), label56, 24, 96);
  gtk_widget_set_size_request (label56, 60, 30);

  label567 = gtk_label_new (_("prenom"));
  gtk_widget_show (label567);
  gtk_fixed_put (GTK_FIXED (fixed13), label567, 0, 144);
  gtk_widget_set_size_request (label567, 90, 25);

  label57 = gtk_label_new (_("cin"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed13), label57, 24, 192);
  gtk_widget_set_size_request (label57, 50, 25);

  label61 = gtk_label_new (_("jour"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed13), label61, 32, 328);
  gtk_widget_set_size_request (label61, 49, 25);

  label65 = gtk_label_new (_("jour"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed13), label65, 32, 416);
  gtk_widget_set_size_request (label65, 49, 25);

  label66 = gtk_label_new (_("mois"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed13), label66, 160, 416);
  gtk_widget_set_size_request (label66, 49, 25);

  label67 = gtk_label_new (_("annee"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed13), label67, 296, 416);
  gtk_widget_set_size_request (label67, 49, 25);

  label63 = gtk_label_new (_("annee"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed13), label63, 304, 328);
  gtk_widget_set_size_request (label63, 49, 25);

  label68 = gtk_label_new (_("type abonnement"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed13), label68, 0, 576);
  gtk_widget_set_size_request (label68, 120, 25);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed13), combobox3, 128, 576);
  gtk_widget_set_size_request (combobox3, 192, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("fitnes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("musculation"));

  label69 = gtk_label_new (_("compt"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed13), label69, 8, 624);
  gtk_widget_set_size_request (label69, 104, 25);

  label58 = gtk_label_new (_("mail"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed13), label58, 32, 536);
  gtk_widget_set_size_request (label58, 49, 25);

  label59 = gtk_label_new (_("telephone"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed13), label59, 24, 488);
  gtk_widget_set_size_request (label59, 88, 30);

  label568 = gtk_label_new (_("mot de pass"));
  gtk_widget_show (label568);
  gtk_fixed_put (GTK_FIXED (fixed13), label568, 0, 240);
  gtk_widget_set_size_request (label568, 88, 25);

  entry106 = gtk_entry_new ();
  gtk_widget_show (entry106);
  gtk_fixed_put (GTK_FIXED (fixed13), entry106, 104, 240);
  gtk_widget_set_size_request (entry106, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry106), 8226);

  label90 = gtk_label_new ("");
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed13), label90, 392, 64);
  gtk_widget_set_size_request (label90, 304, 57);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed13), button13, 408, 680);
  gtk_widget_set_size_request (button13, 122, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button13), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (image1, FALSE);
  GTK_WIDGET_SET_FLAGS (image1, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (image1, GTK_CAN_DEFAULT);

  label515 = gtk_label_new_with_mnemonic (_("    jouter"));
  gtk_widget_show (label515);
  gtk_box_pack_start (GTK_BOX (hbox1), label515, FALSE, FALSE, 0);

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed13), combobox4, 128, 624);
  gtk_widget_set_size_request (combobox4, 192, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("adheren"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("kine"));

  label569 = gtk_label_new (_("<span font_desc=\"Purisa\" foreground =\"purple\" size=\"large\"><b>Ajout d'un nouveaux compt</b></span>"));
  gtk_widget_show (label569);
  gtk_fixed_put (GTK_FIXED (fixed13), label569, 488, 16);
  gtk_widget_set_size_request (label569, 344, 64);
  gtk_label_set_use_markup (GTK_LABEL (label569), TRUE);

  label571 = gtk_label_new (_("<span font_desc=\"italic\" foreground =\"red\" size=\"large\"><b>// sera defini comme login</b></span>"));
  gtk_widget_show (label571);
  gtk_fixed_put (GTK_FIXED (fixed13), label571, 312, 192);
  gtk_widget_set_size_request (label571, 232, 25);
  gtk_label_set_use_markup (GTK_LABEL (label571), TRUE);

  label570 = gtk_label_new (_("<span font_desc=\"Purisa\" foreground =\"purple\"  size=\"large\"><b> Ajouter_compts</b></span>"));
  gtk_widget_show (label570);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label570);
  gtk_label_set_use_markup (GTK_LABEL (label570), TRUE);

  label574 = gtk_label_new (_("MyGym"));
  gtk_widget_show (label574);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label574);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_container_add (GTK_CONTAINER (notebook3), vbox12);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox11, TRUE, TRUE, 0);

  image10 = create_pixmap (admin, "Admin-icon.png");
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox11), image10, TRUE, TRUE, 0);
  gtk_widget_set_size_request (image10, 320, 420);

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_box_pack_start (GTK_BOX (hbox11), fixed22, TRUE, TRUE, 0);

  entry107 = gtk_entry_new ();
  gtk_widget_show (entry107);
  gtk_fixed_put (GTK_FIXED (fixed22), entry107, 152, 176);
  gtk_widget_set_size_request (entry107, 248, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry107), 8226);

  entry108 = gtk_entry_new ();
  gtk_widget_show (entry108);
  gtk_fixed_put (GTK_FIXED (fixed22), entry108, 152, 224);
  gtk_widget_set_size_request (entry108, 248, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry108), 8226);

  label580 = gtk_label_new (_("\n<span font_desc=\"Purisa\" foreground =\"purple\" size=\"large\"><b>Aajouter un nouveau administrateur </b></span>"));
  gtk_widget_show (label580);
  gtk_fixed_put (GTK_FIXED (fixed22), label580, 56, 16);
  gtk_widget_set_size_request (label580, 392, 80);
  gtk_label_set_use_markup (GTK_LABEL (label580), TRUE);

  label579 = gtk_label_new (_("mot de pass"));
  gtk_widget_show (label579);
  gtk_fixed_put (GTK_FIXED (fixed22), label579, 32, 224);
  gtk_widget_set_size_request (label579, 104, 25);

  label578 = gtk_label_new (_("username"));
  gtk_widget_show (label578);
  gtk_fixed_put (GTK_FIXED (fixed22), label578, 40, 176);
  gtk_widget_set_size_request (label578, 96, 25);

  ajouter_admin = gtk_button_new ();
  gtk_widget_show (ajouter_admin);
  gtk_fixed_put (GTK_FIXED (fixed22), ajouter_admin, 288, 336);
  gtk_widget_set_size_request (ajouter_admin, 128, 37);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (ajouter_admin), alignment10);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox12);

  image11 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox12), image11, FALSE, FALSE, 0);

  label581 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label581);
  gtk_box_pack_start (GTK_BOX (hbox12), label581, FALSE, FALSE, 2);
  gtk_widget_set_size_request (label581, 70, 25);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_box_pack_start (GTK_BOX (vbox12), treeview4, TRUE, TRUE, 0);

  label575 = gtk_label_new (_("Ajout_Admin"));
  gtk_widget_show (label575);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label575);

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_box_pack_start (GTK_BOX (vbox6), fixed19, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) admin, "set_focus",
                    G_CALLBACK (on_admin_set_focus),
                    NULL);
  g_signal_connect ((gpointer) notebook1, "select_page",
                    G_CALLBACK (on_notebook1_select_page),
                    NULL);
  g_signal_connect ((gpointer) affichetree, "clicked",
                    G_CALLBACK (on_affichetree_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_as_admin, "clicked",
                    G_CALLBACK (on_modifier_as_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_as_admin, "clicked",
                    G_CALLBACK (on_supprimer_as_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_admin, "clicked",
                    G_CALLBACK (on_ajouter_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (admin, admin, "admin");
  GLADE_HOOKUP_OBJECT (admin, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (admin, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (admin, image12, "image12");
  GLADE_HOOKUP_OBJECT (admin, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (admin, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (admin, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (admin, label582, "label582");
  GLADE_HOOKUP_OBJECT (admin, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (admin, list1, "list1");
  GLADE_HOOKUP_OBJECT (admin, curve1, "curve1");
  GLADE_HOOKUP_OBJECT (admin, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (admin, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (admin, list2, "list2");
  GLADE_HOOKUP_OBJECT (admin, label573, "label573");
  GLADE_HOOKUP_OBJECT (admin, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (admin, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (admin, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (admin, label42, "label42");
  GLADE_HOOKUP_OBJECT (admin, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (admin, label576, "label576");
  GLADE_HOOKUP_OBJECT (admin, affichetree, "affichetree");
  GLADE_HOOKUP_OBJECT (admin, fixed21, "fixed21");
  GLADE_HOOKUP_OBJECT (admin, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (admin, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (admin, refraiche, "refraiche");
  GLADE_HOOKUP_OBJECT (admin, button16, "button16");
  GLADE_HOOKUP_OBJECT (admin, button17, "button17");
  GLADE_HOOKUP_OBJECT (admin, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (admin, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (admin, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (admin, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (admin, label38, "label38");
  GLADE_HOOKUP_OBJECT (admin, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (admin, label43, "label43");
  GLADE_HOOKUP_OBJECT (admin, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (admin, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (admin, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (admin, label39, "label39");
  GLADE_HOOKUP_OBJECT (admin, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (admin, label54, "label54");
  GLADE_HOOKUP_OBJECT (admin, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (admin, spinbutton26, "spinbutton26");
  GLADE_HOOKUP_OBJECT (admin, label55, "label55");
  GLADE_HOOKUP_OBJECT (admin, modifier_as_admin, "modifier_as_admin");
  GLADE_HOOKUP_OBJECT (admin, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (admin, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (admin, image4, "image4");
  GLADE_HOOKUP_OBJECT (admin, label548, "label548");
  GLADE_HOOKUP_OBJECT (admin, supprimer_as_admin, "supprimer_as_admin");
  GLADE_HOOKUP_OBJECT (admin, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (admin, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (admin, image5, "image5");
  GLADE_HOOKUP_OBJECT (admin, supprime123, "supprime123");
  GLADE_HOOKUP_OBJECT (admin, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (admin, label572, "label572");
  GLADE_HOOKUP_OBJECT (admin, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (admin, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (admin, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (admin, label62, "label62");
  GLADE_HOOKUP_OBJECT (admin, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (admin, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (admin, spinbutton13, "spinbutton13");
  GLADE_HOOKUP_OBJECT (admin, spinbutton14, "spinbutton14");
  GLADE_HOOKUP_OBJECT (admin, label64, "label64");
  GLADE_HOOKUP_OBJECT (admin, label60, "label60");
  GLADE_HOOKUP_OBJECT (admin, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (admin, spinbutton15, "spinbutton15");
  GLADE_HOOKUP_OBJECT (admin, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (admin, spinbutton16, "spinbutton16");
  GLADE_HOOKUP_OBJECT (admin, entry105, "entry105");
  GLADE_HOOKUP_OBJECT (admin, label56, "label56");
  GLADE_HOOKUP_OBJECT (admin, label567, "label567");
  GLADE_HOOKUP_OBJECT (admin, label57, "label57");
  GLADE_HOOKUP_OBJECT (admin, label61, "label61");
  GLADE_HOOKUP_OBJECT (admin, label65, "label65");
  GLADE_HOOKUP_OBJECT (admin, label66, "label66");
  GLADE_HOOKUP_OBJECT (admin, label67, "label67");
  GLADE_HOOKUP_OBJECT (admin, label63, "label63");
  GLADE_HOOKUP_OBJECT (admin, label68, "label68");
  GLADE_HOOKUP_OBJECT (admin, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (admin, label69, "label69");
  GLADE_HOOKUP_OBJECT (admin, label58, "label58");
  GLADE_HOOKUP_OBJECT (admin, label59, "label59");
  GLADE_HOOKUP_OBJECT (admin, label568, "label568");
  GLADE_HOOKUP_OBJECT (admin, entry106, "entry106");
  GLADE_HOOKUP_OBJECT (admin, label90, "label90");
  GLADE_HOOKUP_OBJECT (admin, button13, "button13");
  GLADE_HOOKUP_OBJECT (admin, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (admin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (admin, image1, "image1");
  GLADE_HOOKUP_OBJECT (admin, label515, "label515");
  GLADE_HOOKUP_OBJECT (admin, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (admin, label569, "label569");
  GLADE_HOOKUP_OBJECT (admin, label571, "label571");
  GLADE_HOOKUP_OBJECT (admin, label570, "label570");
  GLADE_HOOKUP_OBJECT (admin, label574, "label574");
  GLADE_HOOKUP_OBJECT (admin, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (admin, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (admin, image10, "image10");
  GLADE_HOOKUP_OBJECT (admin, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (admin, entry107, "entry107");
  GLADE_HOOKUP_OBJECT (admin, entry108, "entry108");
  GLADE_HOOKUP_OBJECT (admin, label580, "label580");
  GLADE_HOOKUP_OBJECT (admin, label579, "label579");
  GLADE_HOOKUP_OBJECT (admin, label578, "label578");
  GLADE_HOOKUP_OBJECT (admin, ajouter_admin, "ajouter_admin");
  GLADE_HOOKUP_OBJECT (admin, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (admin, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (admin, image11, "image11");
  GLADE_HOOKUP_OBJECT (admin, label581, "label581");
  GLADE_HOOKUP_OBJECT (admin, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (admin, label575, "label575");
  GLADE_HOOKUP_OBJECT (admin, fixed19, "fixed19");

  gtk_widget_grab_focus (image1);
  gtk_widget_grab_default (image1);
  return admin;
}

GtkWidget*
create_error (void)
{
  GtkWidget *error;
  GtkWidget *fixed4;
  GtkWidget *label564;
  GtkWidget *label563;
  GtkWidget *label34;
  GtkWidget *button14;
  GtkWidget *alignment9;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label577;
  GtkWidget *button10;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *label565;

  error = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (error, 592, 300);
  gtk_window_set_title (GTK_WINDOW (error), _("error"));
  gtk_window_set_position (GTK_WINDOW (error), GTK_WIN_POS_CENTER_ON_PARENT);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (error), fixed4);

  label564 = gtk_label_new (_("<span font_desc=\"italic\" foreground =\"red\" size=\"large\"><b>essayer de nouveau</b></span>"));
  gtk_widget_show (label564);
  gtk_fixed_put (GTK_FIXED (fixed4), label564, 80, 144);
  gtk_widget_set_size_request (label564, 272, 72);
  gtk_label_set_use_markup (GTK_LABEL (label564), TRUE);

  label563 = gtk_label_new (_("<span font_desc=\"italic\" foreground =\"red\" size=\"large\"><b>voulez-vous creer un compt</b></span>"));
  gtk_widget_show (label563);
  gtk_fixed_put (GTK_FIXED (fixed4), label563, 80, 256);
  gtk_widget_set_size_request (label563, 280, 48);
  gtk_label_set_use_markup (GTK_LABEL (label563), TRUE);

  label34 = gtk_label_new (_("<span font_desc=\"Purisa\" foreground =\"red\" size=\"large\"><b>!!!!!!! DESOLE MOT DE PASS OU LOGGIN !!!!! \n               EST ERONE</b></span>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 16, 32);
  gtk_widget_set_size_request (label34, 576, 96);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed4), button14, 384, 160);
  gtk_widget_set_size_request (button14, 144, 45);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button14), alignment9);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label577 = gtk_label_new_with_mnemonic (_("reessayer"));
  gtk_widget_show (label577);
  gtk_box_pack_start (GTK_BOX (hbox8), label577, FALSE, FALSE, 0);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed4), button10, 384, 256);
  gtk_widget_set_size_request (button10, 144, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button10), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  label565 = gtk_label_new_with_mnemonic (_("s'inscrire"));
  gtk_widget_show (label565);
  gtk_box_pack_start (GTK_BOX (hbox7), label565, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (error, error, "error");
  GLADE_HOOKUP_OBJECT (error, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (error, label564, "label564");
  GLADE_HOOKUP_OBJECT (error, label563, "label563");
  GLADE_HOOKUP_OBJECT (error, label34, "label34");
  GLADE_HOOKUP_OBJECT (error, button14, "button14");
  GLADE_HOOKUP_OBJECT (error, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (error, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (error, image9, "image9");
  GLADE_HOOKUP_OBJECT (error, label577, "label577");
  GLADE_HOOKUP_OBJECT (error, button10, "button10");
  GLADE_HOOKUP_OBJECT (error, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (error, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (error, label565, "label565");

  return error;
}

GtkWidget*
create_medecin (void)
{
  GtkWidget *medecin;
  GtkWidget *fixed5;
  GtkWidget *label6;
  GtkWidget *usernamemed;
  GtkWidget *passwordmed;

  medecin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (medecin, 375, 200);
  gtk_window_set_title (GTK_WINDOW (medecin), _("medecin"));
  gtk_window_set_position (GTK_WINDOW (medecin), GTK_WIN_POS_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (medecin), fixed5);

  label6 = gtk_label_new (_("bienvenu medecin"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed5), label6, 40, 8);
  gtk_widget_set_size_request (label6, 272, 65);

  usernamemed = gtk_label_new ("");
  gtk_widget_show (usernamemed);
  gtk_fixed_put (GTK_FIXED (fixed5), usernamemed, 104, 80);
  gtk_widget_set_size_request (usernamemed, 200, 41);

  passwordmed = gtk_label_new ("");
  gtk_widget_show (passwordmed);
  gtk_fixed_put (GTK_FIXED (fixed5), passwordmed, 136, 160);
  gtk_widget_set_size_request (passwordmed, 136, 33);

  g_signal_connect ((gpointer) medecin, "activate_default",
                    G_CALLBACK (on_medecin_activate_default),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (medecin, medecin, "medecin");
  GLADE_HOOKUP_OBJECT (medecin, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (medecin, label6, "label6");
  GLADE_HOOKUP_OBJECT (medecin, usernamemed, "usernamemed");
  GLADE_HOOKUP_OBJECT (medecin, passwordmed, "passwordmed");

  return medecin;
}

GtkWidget*
create_signin (void)
{
  GtkWidget *signin;
  GtkWidget *fixed6;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label28;
  GtkWidget *label25;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label29;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label30;
  GtkWidget *label27;
  GtkWidget *label26;
  GtkWidget *button4;
  GtkWidget *label23;
  GtkWidget *label33;
  GtkWidget *label22;
  GtkWidget *label37;
  GtkWidget *label24;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *combobox1;
  GtkWidget *combobox2;

  signin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (signin, 574, 600);
  gtk_window_set_title (GTK_WINDOW (signin), _("signin"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (signin), fixed6);
  gtk_widget_set_size_request (fixed6, 338, 600);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed6), entry3, 136, 64);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed6), entry4, 136, 104);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed6), entry5, 136, 144);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label8 = gtk_label_new (_("mail"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed6), label8, 8, 104);
  gtk_widget_set_size_request (label8, 120, 25);

  label9 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed6), label9, 16, 144);
  gtk_widget_set_size_request (label9, 120, 25);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton1, 72, 328);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton2, 184, 328);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (2018, 2018, 2500, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton3, 320, 328);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label28 = gtk_label_new (_("annee"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 256, 328);
  gtk_widget_set_size_request (label28, 60, 30);

  label25 = gtk_label_new (_("Date debut d'abonnement"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed6), label25, 80, 288);
  gtk_widget_set_size_request (label25, 200, 30);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton4, 72, 408);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  label29 = gtk_label_new (_("date fin d'abonnement"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 96, 368);
  gtk_widget_set_size_request (label29, 150, 30);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton5, 192, 408);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (2018, 2018, 2500, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton6, 328, 408);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label31 = gtk_label_new (_("mois"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 136, 408);
  gtk_widget_set_size_request (label31, 60, 30);

  label32 = gtk_label_new (_("annee"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed6), label32, 264, 408);
  gtk_widget_set_size_request (label32, 60, 25);

  label30 = gtk_label_new (_("jour"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed6), label30, 16, 408);
  gtk_widget_set_size_request (label30, 60, 30);

  label27 = gtk_label_new (_("mois"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed6), label27, 128, 328);
  gtk_widget_set_size_request (label27, 55, 30);

  label26 = gtk_label_new (_("jour"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed6), label26, 16, 328);
  gtk_widget_set_size_request (label26, 60, 25);

  button4 = gtk_button_new_with_mnemonic (_("signin"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed6), button4, 288, 472);
  gtk_widget_set_size_request (button4, 128, 37);

  label23 = gtk_label_new (_("numero telephone"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed6), label23, 0, 184);
  gtk_widget_set_size_request (label23, 129, 25);

  label33 = gtk_label_new (_("inscription"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 128, 0);
  gtk_widget_set_size_request (label33, 216, 40);

  label22 = gtk_label_new (_("nom&prenom"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed6), label22, 8, 64);
  gtk_widget_set_size_request (label22, 120, 25);

  label37 = gtk_label_new (_("label37"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed6), label37, 320, 64);
  gtk_widget_set_size_request (label37, 64, 25);

  label24 = gtk_label_new (_("type abonnement"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed6), label24, 0, 224);
  gtk_widget_set_size_request (label24, 136, 25);

  spinbutton7_adj = gtk_adjustment_new (0, 0, 100000000, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton7, 136, 184);
  gtk_widget_set_size_request (spinbutton7, 150, 28);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox1, 136, 224);
  gtk_widget_set_size_request (combobox1, 150, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("fitness"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("...."));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (combobox1), TRUE);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox2, 392, 56);
  gtk_widget_set_size_request (combobox2, 150, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("adherent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("coach"));

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (signin, signin, "signin");
  GLADE_HOOKUP_OBJECT (signin, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (signin, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (signin, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (signin, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (signin, label8, "label8");
  GLADE_HOOKUP_OBJECT (signin, label9, "label9");
  GLADE_HOOKUP_OBJECT (signin, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (signin, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (signin, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (signin, label28, "label28");
  GLADE_HOOKUP_OBJECT (signin, label25, "label25");
  GLADE_HOOKUP_OBJECT (signin, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (signin, label29, "label29");
  GLADE_HOOKUP_OBJECT (signin, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (signin, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (signin, label31, "label31");
  GLADE_HOOKUP_OBJECT (signin, label32, "label32");
  GLADE_HOOKUP_OBJECT (signin, label30, "label30");
  GLADE_HOOKUP_OBJECT (signin, label27, "label27");
  GLADE_HOOKUP_OBJECT (signin, label26, "label26");
  GLADE_HOOKUP_OBJECT (signin, button4, "button4");
  GLADE_HOOKUP_OBJECT (signin, label23, "label23");
  GLADE_HOOKUP_OBJECT (signin, label33, "label33");
  GLADE_HOOKUP_OBJECT (signin, label22, "label22");
  GLADE_HOOKUP_OBJECT (signin, label37, "label37");
  GLADE_HOOKUP_OBJECT (signin, label24, "label24");
  GLADE_HOOKUP_OBJECT (signin, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (signin, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (signin, combobox2, "combobox2");

  return signin;
}

GtkWidget*
create_adherent (void)
{
  GtkWidget *adherent;
  GtkWidget *notebook2;
  GtkWidget *vbox5;
  GtkWidget *fixed14;
  GtkWidget *label537adh;
  GtkWidget *label536adh;
  GtkWidget *label535adh;
  GtkWidget *label534adh;
  GtkWidget *label533adh;
  GtkWidget *label532adh;
  GtkWidget *label595;
  GtkWidget *label596;
  GtkWidget *label589;
  GtkWidget *label590;
  GtkWidget *label593;
  GtkWidget *label592;
  GtkWidget *label591;
  GtkWidget *label588;
  GtkWidget *label524adh;
  GtkWidget *fixed26;
  GtkWidget *label599;
  GtkWidget *label598;
  GtkWidget *label597;
  GtkWidget *label600;
  GtkWidget *label594;
  GtkWidget *fixed16;
  GtkWidget *combobox7;
  GtkWidget *combobox8adh;
  GtkWidget *label551adh;
  GtkWidget *label549adh;
  GtkWidget *label583;
  GtkWidget *label550adh;
  GtkWidget *label587;
  GtkWidget *label586;
  GtkWidget *label585;
  GtkWidget *label584;
  GtkWidget *label525adh;
  GtkWidget *vbox13;
  GtkWidget *treeview5;
  GtkWidget *label526adh;
  GtkWidget *fixed15;
  GtkObject *spinbutton20_adj;
  GtkWidget *spinbutton20;
  GtkObject *spinbutton21_adj;
  GtkWidget *spinbutton21;
  GtkObject *spinbutton22_adj;
  GtkWidget *spinbutton22;
  GtkWidget *label541adh;
  GtkWidget *label542adh;
  GtkWidget *label543adh;
  GtkWidget *combobox5adh;
  GtkWidget *combobox6adh;
  GtkWidget *button15adh;
  GtkWidget *label530adh;
  GtkWidget *fixed24;
  GtkWidget *label531adh;
  GtkWidget *empty_notebook_page;
  GtkWidget *label541;
  GtkWidget *label542;

  adherent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (adherent, 800, 700);
  gtk_window_set_title (GTK_WINDOW (adherent), _("adherent"));

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (adherent), notebook2);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (notebook2), vbox5);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_box_pack_start (GTK_BOX (vbox5), fixed14, TRUE, TRUE, 0);

  label537adh = gtk_label_new (_("type abonnement"));
  gtk_widget_show (label537adh);
  gtk_fixed_put (GTK_FIXED (fixed14), label537adh, 24, 384);
  gtk_widget_set_size_request (label537adh, 144, 25);

  label536adh = gtk_label_new (_("Date debut"));
  gtk_widget_show (label536adh);
  gtk_fixed_put (GTK_FIXED (fixed14), label536adh, 24, 320);
  gtk_widget_set_size_request (label536adh, 136, 25);

  label535adh = gtk_label_new (_("telephone"));
  gtk_widget_show (label535adh);
  gtk_fixed_put (GTK_FIXED (fixed14), label535adh, 24, 272);
  gtk_widget_set_size_request (label535adh, 136, 25);

  label534adh = gtk_label_new (_("mail"));
  gtk_widget_show (label534adh);
  gtk_fixed_put (GTK_FIXED (fixed14), label534adh, 8, 224);
  gtk_widget_set_size_request (label534adh, 144, 25);

  label533adh = gtk_label_new (_("cin"));
  gtk_widget_show (label533adh);
  gtk_fixed_put (GTK_FIXED (fixed14), label533adh, 16, 176);
  gtk_widget_set_size_request (label533adh, 136, 25);

  label532adh = gtk_label_new (_("nom"));
  gtk_widget_show (label532adh);
  gtk_fixed_put (GTK_FIXED (fixed14), label532adh, 24, 72);
  gtk_widget_set_size_request (label532adh, 120, 25);

  label595 = gtk_label_new (_("prenom"));
  gtk_widget_show (label595);
  gtk_fixed_put (GTK_FIXED (fixed14), label595, 40, 128);
  gtk_widget_set_size_request (label595, 80, 25);

  label596 = gtk_label_new (_("label596"));
  gtk_widget_show (label596);
  gtk_fixed_put (GTK_FIXED (fixed14), label596, 312, 120);
  gtk_widget_set_size_request (label596, 96, 25);

  label589 = gtk_label_new (_("label589"));
  gtk_widget_show (label589);
  gtk_fixed_put (GTK_FIXED (fixed14), label589, 304, 176);
  gtk_widget_set_size_request (label589, 112, 25);

  label590 = gtk_label_new (_("label590"));
  gtk_widget_show (label590);
  gtk_fixed_put (GTK_FIXED (fixed14), label590, 296, 224);
  gtk_widget_set_size_request (label590, 120, 25);

  label593 = gtk_label_new (_("label593"));
  gtk_widget_show (label593);
  gtk_fixed_put (GTK_FIXED (fixed14), label593, 288, 384);
  gtk_widget_set_size_request (label593, 136, 25);

  label592 = gtk_label_new (_("label592"));
  gtk_widget_show (label592);
  gtk_fixed_put (GTK_FIXED (fixed14), label592, 304, 328);
  gtk_widget_set_size_request (label592, 105, 25);

  label591 = gtk_label_new (_("label591"));
  gtk_widget_show (label591);
  gtk_fixed_put (GTK_FIXED (fixed14), label591, 296, 272);
  gtk_widget_set_size_request (label591, 121, 25);

  label588 = gtk_label_new ("");
  gtk_widget_show (label588);
  gtk_fixed_put (GTK_FIXED (fixed14), label588, 200, 72);
  gtk_widget_set_size_request (label588, 216, 32);

  label524adh = gtk_label_new (_("Profile"));
  gtk_widget_show (label524adh);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label524adh);

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed26);

  label599 = gtk_label_new (_("label599"));
  gtk_widget_show (label599);
  gtk_fixed_put (GTK_FIXED (fixed26), label599, 120, 256);
  gtk_widget_set_size_request (label599, 88, 25);

  label598 = gtk_label_new (_("mail"));
  gtk_widget_show (label598);
  gtk_fixed_put (GTK_FIXED (fixed26), label598, 112, 184);
  gtk_widget_set_size_request (label598, 96, 33);

  label597 = gtk_label_new (_("telephone"));
  gtk_widget_show (label597);
  gtk_fixed_put (GTK_FIXED (fixed26), label597, 96, 120);
  gtk_widget_set_size_request (label597, 112, 25);

  label600 = gtk_label_new (_("cin"));
  gtk_widget_show (label600);
  gtk_fixed_put (GTK_FIXED (fixed26), label600, 104, 64);
  gtk_widget_set_size_request (label600, 96, 31);

  label594 = gtk_label_new (_("modifier"));
  gtk_widget_show (label594);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label594);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed16);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed16), combobox7, 288, 184);
  gtk_widget_set_size_request (combobox7, 33, 31);

  combobox8adh = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8adh);
  gtk_fixed_put (GTK_FIXED (fixed16), combobox8adh, 296, 256);
  gtk_widget_set_size_request (combobox8adh, 33, 31);

  label551adh = gtk_label_new (_("antecedents medicaux"));
  gtk_widget_show (label551adh);
  gtk_fixed_put (GTK_FIXED (fixed16), label551adh, 64, 352);
  gtk_widget_set_size_request (label551adh, 168, 16);

  label549adh = gtk_label_new (_("poids"));
  gtk_widget_show (label549adh);
  gtk_fixed_put (GTK_FIXED (fixed16), label549adh, 88, 128);
  gtk_widget_set_size_request (label549adh, 57, 17);

  label583 = gtk_label_new (_("IMC\n"));
  gtk_widget_show (label583);
  gtk_fixed_put (GTK_FIXED (fixed16), label583, 72, 272);
  gtk_widget_set_size_request (label583, 96, 24);

  label550adh = gtk_label_new (_("taille"));
  gtk_widget_show (label550adh);
  gtk_fixed_put (GTK_FIXED (fixed16), label550adh, 56, 192);
  gtk_widget_set_size_request (label550adh, 120, 25);

  label587 = gtk_label_new (_("label587"));
  gtk_widget_show (label587);
  gtk_fixed_put (GTK_FIXED (fixed16), label587, 280, 336);
  gtk_widget_set_size_request (label587, 120, 33);

  label586 = gtk_label_new (_("label586"));
  gtk_widget_show (label586);
  gtk_fixed_put (GTK_FIXED (fixed16), label586, 272, 256);
  gtk_widget_set_size_request (label586, 112, 33);

  label585 = gtk_label_new (_("label585"));
  gtk_widget_show (label585);
  gtk_fixed_put (GTK_FIXED (fixed16), label585, 264, 184);
  gtk_widget_set_size_request (label585, 120, 32);

  label584 = gtk_label_new (_("label584"));
  gtk_widget_show (label584);
  gtk_fixed_put (GTK_FIXED (fixed16), label584, 280, 120);
  gtk_widget_set_size_request (label584, 104, 25);

  label525adh = gtk_label_new (_("fiche medicale"));
  gtk_widget_show (label525adh);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label525adh);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_container_add (GTK_CONTAINER (notebook2), vbox13);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_box_pack_start (GTK_BOX (vbox13), treeview5, TRUE, TRUE, 0);
  gtk_widget_set_size_request (treeview5, 300, 200);

  label526adh = gtk_label_new (_("coach_et_staff"));
  gtk_widget_show (label526adh);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label526adh);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed15);

  spinbutton20_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton20 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton20_adj), 1, 0);
  gtk_widget_show (spinbutton20);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton20, 168, 168);
  gtk_widget_set_size_request (spinbutton20, 60, 27);

  spinbutton21_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton21 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton21_adj), 1, 0);
  gtk_widget_show (spinbutton21);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton21, 304, 168);
  gtk_widget_set_size_request (spinbutton21, 60, 27);

  spinbutton22_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton22 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton22_adj), 1, 0);
  gtk_widget_show (spinbutton22);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton22, 440, 168);
  gtk_widget_set_size_request (spinbutton22, 60, 27);

  label541adh = gtk_label_new (_("date"));
  gtk_widget_show (label541adh);
  gtk_fixed_put (GTK_FIXED (fixed15), label541adh, 32, 176);
  gtk_widget_set_size_request (label541adh, 57, 17);

  label542adh = gtk_label_new (_("heure"));
  gtk_widget_show (label542adh);
  gtk_fixed_put (GTK_FIXED (fixed15), label542adh, 40, 256);
  gtk_widget_set_size_request (label542adh, 57, 17);

  label543adh = gtk_label_new (_("destinataire"));
  gtk_widget_show (label543adh);
  gtk_fixed_put (GTK_FIXED (fixed15), label543adh, 8, 328);
  gtk_widget_set_size_request (label543adh, 120, 25);

  combobox5adh = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5adh);
  gtk_fixed_put (GTK_FIXED (fixed15), combobox5adh, 136, 248);
  gtk_widget_set_size_request (combobox5adh, 224, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5adh), _("8h==9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5adh), _("10===12"));

  combobox6adh = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6adh);
  gtk_fixed_put (GTK_FIXED (fixed15), combobox6adh, 144, 320);
  gtk_widget_set_size_request (combobox6adh, 216, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6adh), _("fooulen klkj"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6adh), _("fghgf "));

  button15adh = gtk_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (button15adh);
  gtk_fixed_put (GTK_FIXED (fixed15), button15adh, 392, 424);
  gtk_widget_set_size_request (button15adh, 104, 37);

  label530adh = gtk_label_new (_("rendez-vous"));
  gtk_widget_show (label530adh);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 4), label530adh);

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed24);

  label531adh = gtk_label_new (_("evenement"));
  gtk_widget_show (label531adh);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 5), label531adh);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label541 = gtk_label_new ("");
  gtk_widget_show (label541);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 6), label541);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label542 = gtk_label_new ("");
  gtk_widget_show (label542);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 7), label542);

  g_signal_connect ((gpointer) adherent, "set_focus",
                    G_CALLBACK (on_adherent_set_focus),
                    NULL);
  g_signal_connect ((gpointer) button15adh, "clicked",
                    G_CALLBACK (on_button15adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (adherent, adherent, "adherent");
  GLADE_HOOKUP_OBJECT (adherent, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (adherent, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (adherent, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (adherent, label537adh, "label537adh");
  GLADE_HOOKUP_OBJECT (adherent, label536adh, "label536adh");
  GLADE_HOOKUP_OBJECT (adherent, label535adh, "label535adh");
  GLADE_HOOKUP_OBJECT (adherent, label534adh, "label534adh");
  GLADE_HOOKUP_OBJECT (adherent, label533adh, "label533adh");
  GLADE_HOOKUP_OBJECT (adherent, label532adh, "label532adh");
  GLADE_HOOKUP_OBJECT (adherent, label595, "label595");
  GLADE_HOOKUP_OBJECT (adherent, label596, "label596");
  GLADE_HOOKUP_OBJECT (adherent, label589, "label589");
  GLADE_HOOKUP_OBJECT (adherent, label590, "label590");
  GLADE_HOOKUP_OBJECT (adherent, label593, "label593");
  GLADE_HOOKUP_OBJECT (adherent, label592, "label592");
  GLADE_HOOKUP_OBJECT (adherent, label591, "label591");
  GLADE_HOOKUP_OBJECT (adherent, label588, "label588");
  GLADE_HOOKUP_OBJECT (adherent, label524adh, "label524adh");
  GLADE_HOOKUP_OBJECT (adherent, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (adherent, label599, "label599");
  GLADE_HOOKUP_OBJECT (adherent, label598, "label598");
  GLADE_HOOKUP_OBJECT (adherent, label597, "label597");
  GLADE_HOOKUP_OBJECT (adherent, label600, "label600");
  GLADE_HOOKUP_OBJECT (adherent, label594, "label594");
  GLADE_HOOKUP_OBJECT (adherent, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (adherent, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (adherent, combobox8adh, "combobox8adh");
  GLADE_HOOKUP_OBJECT (adherent, label551adh, "label551adh");
  GLADE_HOOKUP_OBJECT (adherent, label549adh, "label549adh");
  GLADE_HOOKUP_OBJECT (adherent, label583, "label583");
  GLADE_HOOKUP_OBJECT (adherent, label550adh, "label550adh");
  GLADE_HOOKUP_OBJECT (adherent, label587, "label587");
  GLADE_HOOKUP_OBJECT (adherent, label586, "label586");
  GLADE_HOOKUP_OBJECT (adherent, label585, "label585");
  GLADE_HOOKUP_OBJECT (adherent, label584, "label584");
  GLADE_HOOKUP_OBJECT (adherent, label525adh, "label525adh");
  GLADE_HOOKUP_OBJECT (adherent, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (adherent, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (adherent, label526adh, "label526adh");
  GLADE_HOOKUP_OBJECT (adherent, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (adherent, spinbutton20, "spinbutton20");
  GLADE_HOOKUP_OBJECT (adherent, spinbutton21, "spinbutton21");
  GLADE_HOOKUP_OBJECT (adherent, spinbutton22, "spinbutton22");
  GLADE_HOOKUP_OBJECT (adherent, label541adh, "label541adh");
  GLADE_HOOKUP_OBJECT (adherent, label542adh, "label542adh");
  GLADE_HOOKUP_OBJECT (adherent, label543adh, "label543adh");
  GLADE_HOOKUP_OBJECT (adherent, combobox5adh, "combobox5adh");
  GLADE_HOOKUP_OBJECT (adherent, combobox6adh, "combobox6adh");
  GLADE_HOOKUP_OBJECT (adherent, button15adh, "button15adh");
  GLADE_HOOKUP_OBJECT (adherent, label530adh, "label530adh");
  GLADE_HOOKUP_OBJECT (adherent, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (adherent, label531adh, "label531adh");
  GLADE_HOOKUP_OBJECT (adherent, label541, "label541");
  GLADE_HOOKUP_OBJECT (adherent, label542, "label542");

  return adherent;
}

GtkWidget*
create_coach (void)
{
  GtkWidget *coach;
  GtkWidget *notebook4;
  GtkWidget *fixed27;
  GtkWidget *label610;
  GtkWidget *label613;
  GtkWidget *label615;
  GtkWidget *label609;
  GtkWidget *label608;
  GtkWidget *label607;
  GtkWidget *label619;
  GtkWidget *label611;
  GtkWidget *label617;
  GtkWidget *label616;
  GtkWidget *label618;
  GtkWidget *label620;
  GtkWidget *label621;
  GtkWidget *label622;
  GtkWidget *label601;
  GtkWidget *fixed28;
  GtkWidget *label633;
  GtkWidget *label634;
  GtkWidget *label635;
  GtkWidget *label636;
  GtkWidget *entry110;
  GtkWidget *entry111;
  GtkWidget *entry112;
  GtkWidget *button20;
  GtkWidget *label602;
  GtkWidget *fixed29;
  GtkWidget *treeview6;
  GtkWidget *label632;
  GtkWidget *button19;
  GtkWidget *label603;
  GtkWidget *fixed30;
  GtkWidget *label625;
  GtkWidget *label626;
  GtkObject *spinbutton27_adj;
  GtkWidget *spinbutton27;
  GtkObject *spinbutton28_adj;
  GtkWidget *spinbutton28;
  GtkObject *spinbutton29_adj;
  GtkWidget *spinbutton29;
  GtkWidget *label627;
  GtkWidget *label630;
  GtkWidget *label631;
  GtkWidget *label628;
  GtkWidget *label629;
  GtkWidget *comboboxentry2;
  GtkWidget *entry109;
  GtkWidget *comboboxentry1;
  GtkWidget *button18;
  GtkWidget *label604;

  coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (coach, 400, 250);
  gtk_window_set_title (GTK_WINDOW (coach), _("coach"));

  notebook4 = gtk_notebook_new ();
  gtk_widget_show (notebook4);
  gtk_container_add (GTK_CONTAINER (coach), notebook4);

  fixed27 = gtk_fixed_new ();
  gtk_widget_show (fixed27);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed27);

  label610 = gtk_label_new (_("adresse e-mail"));
  gtk_widget_show (label610);
  gtk_fixed_put (GTK_FIXED (fixed27), label610, 16, 312);
  gtk_widget_set_size_request (label610, 120, 25);

  label613 = gtk_label_new (_("date de naissance"));
  gtk_widget_show (label613);
  gtk_fixed_put (GTK_FIXED (fixed27), label613, 24, 264);
  gtk_widget_set_size_request (label613, 128, 24);

  label615 = gtk_label_new (_("N.telephone"));
  gtk_widget_show (label615);
  gtk_fixed_put (GTK_FIXED (fixed27), label615, 40, 208);
  gtk_widget_set_size_request (label615, 89, 25);

  label609 = gtk_label_new (_("Cin"));
  gtk_widget_show (label609);
  gtk_fixed_put (GTK_FIXED (fixed27), label609, 40, 168);
  gtk_widget_set_size_request (label609, 80, 24);

  label608 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label608);
  gtk_fixed_put (GTK_FIXED (fixed27), label608, 48, 128);
  gtk_widget_set_size_request (label608, 65, 25);

  label607 = gtk_label_new (_("Nom"));
  gtk_widget_show (label607);
  gtk_fixed_put (GTK_FIXED (fixed27), label607, 48, 80);
  gtk_widget_set_size_request (label607, 64, 33);

  label619 = gtk_label_new (_("label619"));
  gtk_widget_show (label619);
  gtk_fixed_put (GTK_FIXED (fixed27), label619, 208, 208);
  gtk_widget_set_size_request (label619, 104, 32);

  label611 = gtk_label_new (_("specialite"));
  gtk_widget_show (label611);
  gtk_fixed_put (GTK_FIXED (fixed27), label611, 32, 352);
  gtk_widget_set_size_request (label611, 81, 33);

  label617 = gtk_label_new (_("label617"));
  gtk_widget_show (label617);
  gtk_fixed_put (GTK_FIXED (fixed27), label617, 176, 128);
  gtk_widget_set_size_request (label617, 160, 32);

  label616 = gtk_label_new (_("label616"));
  gtk_widget_show (label616);
  gtk_fixed_put (GTK_FIXED (fixed27), label616, 208, 88);
  gtk_widget_set_size_request (label616, 96, 24);

  label618 = gtk_label_new (_("label618"));
  gtk_widget_show (label618);
  gtk_fixed_put (GTK_FIXED (fixed27), label618, 224, 168);
  gtk_widget_set_size_request (label618, 72, 24);

  label620 = gtk_label_new (_("label620"));
  gtk_widget_show (label620);
  gtk_fixed_put (GTK_FIXED (fixed27), label620, 216, 256);
  gtk_widget_set_size_request (label620, 97, 32);

  label621 = gtk_label_new (_("label621"));
  gtk_widget_show (label621);
  gtk_fixed_put (GTK_FIXED (fixed27), label621, 216, 304);
  gtk_widget_set_size_request (label621, 89, 33);

  label622 = gtk_label_new (_("label622"));
  gtk_widget_show (label622);
  gtk_fixed_put (GTK_FIXED (fixed27), label622, 136, 344);
  gtk_widget_set_size_request (label622, 256, 48);

  label601 = gtk_label_new (_("Profile\n"));
  gtk_widget_show (label601);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 0), label601);

  fixed28 = gtk_fixed_new ();
  gtk_widget_show (fixed28);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed28);

  label633 = gtk_label_new ("");
  gtk_widget_show (label633);
  gtk_fixed_put (GTK_FIXED (fixed28), label633, 24, 72);
  gtk_widget_set_size_request (label633, 88, 32);

  label634 = gtk_label_new (_("cin"));
  gtk_widget_show (label634);
  gtk_fixed_put (GTK_FIXED (fixed28), label634, 8, 48);
  gtk_widget_set_size_request (label634, 96, 25);

  label635 = gtk_label_new (_("telephone"));
  gtk_widget_show (label635);
  gtk_fixed_put (GTK_FIXED (fixed28), label635, 16, 120);
  gtk_widget_set_size_request (label635, 96, 40);

  label636 = gtk_label_new (_("email"));
  gtk_widget_show (label636);
  gtk_fixed_put (GTK_FIXED (fixed28), label636, 8, 184);
  gtk_widget_set_size_request (label636, 104, 40);

  entry110 = gtk_entry_new ();
  gtk_widget_show (entry110);
  gtk_fixed_put (GTK_FIXED (fixed28), entry110, 136, 48);
  gtk_widget_set_size_request (entry110, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry110), 8226);

  entry111 = gtk_entry_new ();
  gtk_widget_show (entry111);
  gtk_fixed_put (GTK_FIXED (fixed28), entry111, 144, 128);
  gtk_widget_set_size_request (entry111, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry111), 8226);

  entry112 = gtk_entry_new ();
  gtk_widget_show (entry112);
  gtk_fixed_put (GTK_FIXED (fixed28), entry112, 144, 192);
  gtk_widget_set_size_request (entry112, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry112), 8226);

  button20 = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed28), button20, 192, 288);
  gtk_widget_set_size_request (button20, 120, 48);

  label602 = gtk_label_new (_("modifier"));
  gtk_widget_show (label602);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 1), label602);

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed29);

  treeview6 = gtk_tree_view_new ();
  gtk_widget_show (treeview6);
  gtk_fixed_put (GTK_FIXED (fixed29), treeview6, 0, 64);
  gtk_widget_set_size_request (treeview6, 992, 344);

  label632 = gtk_label_new (_("liste des adherants"));
  gtk_widget_show (label632);
  gtk_fixed_put (GTK_FIXED (fixed29), label632, 0, 24);
  gtk_widget_set_size_request (label632, 400, 32);

  button19 = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed29), button19, 824, 472);
  gtk_widget_set_size_request (button19, 136, 48);

  label603 = gtk_label_new (_("adherant"));
  gtk_widget_show (label603);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 2), label603);

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed30);

  label625 = gtk_label_new (_("nom d`evenement"));
  gtk_widget_show (label625);
  gtk_fixed_put (GTK_FIXED (fixed30), label625, 8, 48);
  gtk_widget_set_size_request (label625, 160, 56);

  label626 = gtk_label_new (_("date d`evenement"));
  gtk_widget_show (label626);
  gtk_fixed_put (GTK_FIXED (fixed30), label626, 24, 112);
  gtk_widget_set_size_request (label626, 152, 41);

  spinbutton27_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton27 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton27_adj), 1, 0);
  gtk_widget_show (spinbutton27);
  gtk_fixed_put (GTK_FIXED (fixed30), spinbutton27, 248, 120);
  gtk_widget_set_size_request (spinbutton27, 64, 27);

  spinbutton28_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton28 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton28_adj), 1, 0);
  gtk_widget_show (spinbutton28);
  gtk_fixed_put (GTK_FIXED (fixed30), spinbutton28, 376, 120);
  gtk_widget_set_size_request (spinbutton28, 60, 27);

  spinbutton29_adj = gtk_adjustment_new (1, 0, 3000, 1, 10, 10);
  spinbutton29 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton29_adj), 1, 0);
  gtk_widget_show (spinbutton29);
  gtk_fixed_put (GTK_FIXED (fixed30), spinbutton29, 512, 120);
  gtk_widget_set_size_request (spinbutton29, 60, 27);

  label627 = gtk_label_new (_("jour"));
  gtk_widget_show (label627);
  gtk_fixed_put (GTK_FIXED (fixed30), label627, 192, 120);
  gtk_widget_set_size_request (label627, 56, 33);

  label630 = gtk_label_new (_("lieu d`evenement"));
  gtk_widget_show (label630);
  gtk_fixed_put (GTK_FIXED (fixed30), label630, 16, 192);
  gtk_widget_set_size_request (label630, 168, 40);

  label631 = gtk_label_new (_("heure d`evenement"));
  gtk_widget_show (label631);
  gtk_fixed_put (GTK_FIXED (fixed30), label631, 24, 272);
  gtk_widget_set_size_request (label631, 152, 33);

  label628 = gtk_label_new (_("mois"));
  gtk_widget_show (label628);
  gtk_fixed_put (GTK_FIXED (fixed30), label628, 320, 120);
  gtk_widget_set_size_request (label628, 56, 25);

  label629 = gtk_label_new (_("annee"));
  gtk_widget_show (label629);
  gtk_fixed_put (GTK_FIXED (fixed30), label629, 448, 120);
  gtk_widget_set_size_request (label629, 64, 25);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed30), comboboxentry2, 208, 272);
  gtk_widget_set_size_request (comboboxentry2, 189, 29);

  entry109 = gtk_entry_new ();
  gtk_widget_show (entry109);
  gtk_fixed_put (GTK_FIXED (fixed30), entry109, 208, 56);
  gtk_widget_set_size_request (entry109, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry109), 8226);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed30), comboboxentry1, 208, 200);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);

  button18 = gtk_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed30), button18, 256, 360);
  gtk_widget_set_size_request (button18, 112, 48);

  label604 = gtk_label_new (_("creer evenement"));
  gtk_widget_show (label604);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 3), label604);

  g_signal_connect ((gpointer) button20, "clicked",
                    G_CALLBACK (on_button20_clicked),
                    NULL);
  g_signal_connect ((gpointer) button19, "leave",
                    G_CALLBACK (on_button19_leave),
                    NULL);
  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button18_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (coach, coach, "coach");
  GLADE_HOOKUP_OBJECT (coach, notebook4, "notebook4");
  GLADE_HOOKUP_OBJECT (coach, fixed27, "fixed27");
  GLADE_HOOKUP_OBJECT (coach, label610, "label610");
  GLADE_HOOKUP_OBJECT (coach, label613, "label613");
  GLADE_HOOKUP_OBJECT (coach, label615, "label615");
  GLADE_HOOKUP_OBJECT (coach, label609, "label609");
  GLADE_HOOKUP_OBJECT (coach, label608, "label608");
  GLADE_HOOKUP_OBJECT (coach, label607, "label607");
  GLADE_HOOKUP_OBJECT (coach, label619, "label619");
  GLADE_HOOKUP_OBJECT (coach, label611, "label611");
  GLADE_HOOKUP_OBJECT (coach, label617, "label617");
  GLADE_HOOKUP_OBJECT (coach, label616, "label616");
  GLADE_HOOKUP_OBJECT (coach, label618, "label618");
  GLADE_HOOKUP_OBJECT (coach, label620, "label620");
  GLADE_HOOKUP_OBJECT (coach, label621, "label621");
  GLADE_HOOKUP_OBJECT (coach, label622, "label622");
  GLADE_HOOKUP_OBJECT (coach, label601, "label601");
  GLADE_HOOKUP_OBJECT (coach, fixed28, "fixed28");
  GLADE_HOOKUP_OBJECT (coach, label633, "label633");
  GLADE_HOOKUP_OBJECT (coach, label634, "label634");
  GLADE_HOOKUP_OBJECT (coach, label635, "label635");
  GLADE_HOOKUP_OBJECT (coach, label636, "label636");
  GLADE_HOOKUP_OBJECT (coach, entry110, "entry110");
  GLADE_HOOKUP_OBJECT (coach, entry111, "entry111");
  GLADE_HOOKUP_OBJECT (coach, entry112, "entry112");
  GLADE_HOOKUP_OBJECT (coach, button20, "button20");
  GLADE_HOOKUP_OBJECT (coach, label602, "label602");
  GLADE_HOOKUP_OBJECT (coach, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (coach, treeview6, "treeview6");
  GLADE_HOOKUP_OBJECT (coach, label632, "label632");
  GLADE_HOOKUP_OBJECT (coach, button19, "button19");
  GLADE_HOOKUP_OBJECT (coach, label603, "label603");
  GLADE_HOOKUP_OBJECT (coach, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (coach, label625, "label625");
  GLADE_HOOKUP_OBJECT (coach, label626, "label626");
  GLADE_HOOKUP_OBJECT (coach, spinbutton27, "spinbutton27");
  GLADE_HOOKUP_OBJECT (coach, spinbutton28, "spinbutton28");
  GLADE_HOOKUP_OBJECT (coach, spinbutton29, "spinbutton29");
  GLADE_HOOKUP_OBJECT (coach, label627, "label627");
  GLADE_HOOKUP_OBJECT (coach, label630, "label630");
  GLADE_HOOKUP_OBJECT (coach, label631, "label631");
  GLADE_HOOKUP_OBJECT (coach, label628, "label628");
  GLADE_HOOKUP_OBJECT (coach, label629, "label629");
  GLADE_HOOKUP_OBJECT (coach, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (coach, entry109, "entry109");
  GLADE_HOOKUP_OBJECT (coach, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (coach, button18, "button18");
  GLADE_HOOKUP_OBJECT (coach, label604, "label604");

  return coach;
}

GtkWidget*
create_dietecien (void)
{
  GtkWidget *dietecien;
  GtkWidget *fixed9;
  GtkWidget *label12;

  dietecien = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (dietecien, 400, 250);
  gtk_window_set_title (GTK_WINDOW (dietecien), _("dietecien"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (dietecien), fixed9);

  label12 = gtk_label_new (_("espace dieteciens"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed9), label12, 72, 56);
  gtk_widget_set_size_request (label12, 256, 129);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dietecien, dietecien, "dietecien");
  GLADE_HOOKUP_OBJECT (dietecien, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (dietecien, label12, "label12");

  return dietecien;
}

GtkWidget*
create_kine (void)
{
  GtkWidget *kine;
  GtkWidget *fixed10;
  GtkWidget *label13;

  kine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (kine, 400, 250);
  gtk_window_set_title (GTK_WINDOW (kine), _("kine"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (kine), fixed10);

  label13 = gtk_label_new (_("espace kine"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed10), label13, 80, 56);
  gtk_widget_set_size_request (label13, 240, 121);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (kine, kine, "kine");
  GLADE_HOOKUP_OBJECT (kine, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (kine, label13, "label13");

  return kine;
}

