/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_home (void);
GtkWidget* create_authentification (void);
GtkWidget* create_admin (void);
GtkWidget* create_error (void);
GtkWidget* create_medecin (void);
GtkWidget* create_signin (void);
GtkWidget* create_adherent (void);
GtkWidget* create_coach (void);
GtkWidget* create_dietecien (void);
GtkWidget* create_kine (void);
